services:
  - type: web
    name: kamaitachi-survey-app # あなたのアプリ名
    runtime: ruby
    plan: free  #追記
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kamaitachi-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: kamaitachi-db
    plan: free  #追記
    databaseName: kamaitachi_survey
    user: kamaitachi_user